services:
  3dgs_slam:
    image: 3dgs_slam:0.3.0
    container_name: 3dgs_slam
    environment:
      - DISPLAY=${DISPLAY}
    volumes:
      - /tmp/.X11-unix:/tmp/.X11-unix
      - ./:/app
    ports:
      - "8000:8000"
    # runtime: nvidia
    deploy:
      resources:
        reservations:
          devices:
            - capabilities: [ gpu ]
    tty: true
    privileged: true
    stdin_open: true
